title: Grigoris Giannis
description: Electronics Engineer & IT Support Specialist
theme: jekyll-theme-midnight

markdown: kramdown

author:
  name: Grigoris Giannis

plugins:
  - jekyll-seo-tag



