title: Grigoris Giannis
description: Electronics Engineer & IT Support Specialist
theme: jekyll-theme-slate

markdown: kramdown

author:
  name: Grigoris Giannis

plugins:
  - jekyll-seo-tag
github:
  is_project_page: false





